M48
; DRILL file {KiCad 8.0.3} date 2024-09-20T13:19:40-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-20T13:19:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X85.787Y-91.11
X85.787Y-96.89
T2
X94.42Y-61.7
X94.42Y-109.7
X127.42Y-61.7
X127.42Y-109.7
T3
X85.0Y-54.0
X85.0Y-128.5
X198.5Y-54.0
X198.5Y-128.5
M30
